services:
  reverseproxy:
    image: parfect-reverseproxy-image
    build: ./reverseproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverseproxy/conf.d:/etc/nginx/conf.d
      - ./reverseproxy/ssl:/etc/nginx/ssl
      - ./reverseproxy/html:/usr/share/nginx/html
      - ./reverseproxy/logs:/var/log/nginx
    depends_on:
      - server
  server:
    image: parfect-server-image
    build: ./server
    ports:
      - "8080:8080"
    env_files:
      - server.env
  database:
    image: partfect-database-image
    build: ./database
    ports:
      - "5432:5432"
    env_files:
      - database.env
